// Single merged design-system token set, combined from every Stitch screen
// export. Every screen used the same Material-3-style token names/values,
// so this union lets any screen's original class names render identically.
// (Moved here from a runtime CDN <script> config so the app has no
// dependency on cdn.tailwindcss.com at runtime.)
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,html}'],
  safelist: [
    // Screens are generated as raw HTML strings, not statically analyzable
    // JSX, so anything not a plain literal class in those files (there are
    // none dynamic today) would need to be listed here too.
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#410006',
        'error-container': '#93000a',
        'tertiary-container': '#8c919b',
        'tertiary-fixed-dim': '#c2c6d1',
        'on-tertiary-fixed': '#171c23',
        'tertiary-fixed': '#dee2ed',
        'surface-container': '#1e2024',
        'secondary-fixed-dim': '#ffb3af',
        'on-error': '#690005',
        'on-tertiary': '#2c3139',
        'on-tertiary-fixed-variant': '#424750',
        'inverse-primary': '#0058cc',
        'secondary-container': '#ad001f',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d9e2ff',
        tertiary: '#c2c6d1',
        'on-primary': '#002c6f',
        'surface-variant': '#333539',
        'on-secondary-container': '#ffb8b4',
        outline: '#8c90a0',
        'on-primary-fixed-variant': '#00419c',
        'inverse-on-surface': '#2f3035',
        'on-background': '#e2e2e8',
        'surface-container-lowest': '#0c0e12',
        'on-secondary': '#68000e',
        'on-secondary-fixed-variant': '#930019',
        'primary-fixed-dim': '#b0c6ff',
        primary: '#b0c6ff',
        surface: '#111317',
        'outline-variant': '#424654',
        'secondary-fixed': '#ffdad8',
        'surface-container-high': '#282a2e',
        'primary-container': '#568cff',
        secondary: '#ffb3af',
        'on-primary-fixed': '#001945',
        'surface-dim': '#111317',
        'surface-container-highest': '#333539',
        'on-primary-container': '#002662',
        'on-tertiary-container': '#252a32',
        background: '#111317',
        'inverse-surface': '#e2e2e8',
        'surface-tint': '#b0c6ff',
        'on-surface-variant': '#c2c6d7',
        'on-surface': '#e2e2e8',
        'surface-bright': '#37393e',
        error: '#ffb4ab',
        'surface-container-low': '#1a1c20',
      },
      borderRadius: { DEFAULT: '0.125rem', lg: '0.25rem', xl: '0.5rem', full: '0.75rem' },
      spacing: {
        'space-xl': '1.5rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'margin-mobile': '0.75rem',
        gutter: '0.5rem',
        'space-lg': '1rem',
        'space-md': '0.75rem',
        'gutter-mobile': '0.5rem',
        margin: '0.75rem',
      },
      fontFamily: {
        'headline-sm': ['Hanken Grotesk'],
        'label-sm': ['Geist'],
        'body-lg': ['Geist'],
        'label-md': ['Geist'],
        'body-md': ['Geist'],
        'headline-md': ['Hanken Grotesk'],
        'headline-xl': ['Hanken Grotesk'],
        'label-lg': ['Geist'],
        'headline-lg': ['Hanken Grotesk'],
        'body-sm': ['Geist'],
      },
      fontSize: {
        'headline-sm': ['15px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '600' }],
        'label-sm': ['9px', { lineHeight: '10px', letterSpacing: '0.08em', fontWeight: '700' }],
        'body-lg': ['15px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['10px', { lineHeight: '12px', letterSpacing: '0.06em', fontWeight: '600' }],
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-md': ['18px', { lineHeight: '22px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-xl': ['32px', { lineHeight: '36px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'label-lg': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['11px', { lineHeight: '14px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
