// AUTO-GENERATED by scripts/generate-screens.mjs
import * as screen0 from './welcome.js';
import * as screen1 from './createAccount.js';
import * as screen2 from './addFirstLeague.js';
import * as screen3 from './scoringRulesUpload.js';
import * as screen4 from './reviewDetectedScoring.js';
import * as screen5 from './scanMyLineup.js';
import * as screen6 from './confirmMyLineup.js';
import * as screen7 from './confirmOpponentLineup.js';
import * as screen8 from './bulkAddLeagues.js';
import * as screen9 from './contextualAlerts.js';
import * as screen10 from './payoffReady.js';
import * as screen11 from './watchNow.js';
import * as screen12 from './itinerary.js';
import * as screen13 from './matchups.js';
import * as screen14 from './players.js';
import * as screen15 from './activity.js';
import * as screen16 from './leaguesHub.js';
import * as screen17 from './weeklySetup.js';

export const generatedScreens = [
  screen0,
  screen1,
  screen2,
  screen3,
  screen4,
  screen5,
  screen6,
  screen7,
  screen8,
  screen9,
  screen10,
  screen11,
  screen12,
  screen13,
  screen14,
  screen15,
  screen16,
  screen17,
];
